export interface ModelInfo {
  id: string;
  name: string;
  providerId: string;
  providerName: string;
  isFree: boolean;
  badge?: string;
  description: string;
  contextLength?: string;
  pricing?: string;
  supportsTools?: boolean;
}

export const SUPPORTED_AI_MODELS: ModelInfo[] = [
  // =========================================================================
  // GOOGLE GEMINI (Générations 2.0, 2.5 et 3.x)
  // =========================================================================
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Recommandé",
    description: "Modèle ultra-rapide optimisé pour le codage autonome et l'orchestration de tools.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Raisonnement",
    description: "Raisonnement avancé pour refactoring complexe, architecture et analyse de bugs profonds.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.0-flash",
    name: "Gemini 3.0 Flash",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Génération 3",
    description: "Nouvelle génération 3.0 ultra-véloce avec capacités multimodales natives et latence minimale.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.0-pro",
    name: "Gemini 3.0 Pro",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Génération 3 Pro",
    description: "Modèle de pointe de génération 3 pour l'ingénierie logicielle et le raisonnement multi-étapes.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini 3.1 Pro",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Ingénierie Avancée",
    description: "Capacité d'abstraction supérieure, analyse de codebases massives et vérification formelle.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Génération 3.5",
    description: "Vitesse phénoménale et capacités de raisonnement hybride de génération 3.5.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.5-pro",
    name: "Gemini 3.5 Pro",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Frontière Ultime",
    description: "Modèle frontière suprême combinant raisonnement profond multi-pass et exécution sans compromis.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.8-flash",
    name: "Gemini 3.8 Flash",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Génération 3.8",
    description: "Dernière évolution Google avec vitesse de traitement ultra-réactive et orchestration outillée.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-3.8-pro",
    name: "Gemini 3.8 Pro",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Génération 3.8 Pro",
    description: "Modèle de pointe 3.8 pour raisonnement étendu, refactoring massif et codage complexe.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Génération 2",
    description: "Vitesse d'exécution exceptionnelle pour le streaming interactif et les tâches en temps réel.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash-Lite",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Flash Lite",
    description: "Variante ultra-légère conçue pour une latence minimale et les micro-tâches de codage.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.0-flash-thinking-exp",
    name: "Gemini 2.0 Flash Thinking",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Thinking Exp",
    description: "Modèle avec processus de pensée dynamique visible pour la résolution algorithmique complexe.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.0-flash-thinking-exp-01-21",
    name: "Gemini 2.0 Thinking (01-21)",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Thinking 01-21",
    description: "Instantané perfectionné du modèle de pensée dynamique pour l'analyse de code approfondie.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-2.0-pro-exp-02-05",
    name: "Gemini 2.0 Pro Experimental",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: false,
    badge: "Génération 2 Pro",
    description: "Modèle de raisonnement lourd pour l'analyse d'AST et la génération de patches stricts.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "gemini-exp-1206",
    name: "Gemini Exp 1206",
    providerId: "google",
    providerName: "Google Gemini",
    isFree: true,
    badge: "Expérience Google",
    description: "Version expérimentale phare avec haute fidélité d'écriture et résolution de bugs.",
    contextLength: "2M tokens",
    supportsTools: true,
  },

  // =========================================================================
  // ANTHROPIC CLAUDE (Génération 3.x)
  // =========================================================================
  {
    id: "claude-3-7-sonnet",
    name: "Claude 3.7 Sonnet",
    providerId: "anthropic",
    providerName: "Anthropic Claude",
    isFree: false,
    badge: "Hybride Pensée/Code",
    description: "Le modèle hybride de pointe avec réflexion dynamique et excellence absolue en ingénierie logicielle.",
    contextLength: "200k tokens",
    supportsTools: true,
  },
  {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    providerId: "anthropic",
    providerName: "Anthropic Claude",
    isFree: false,
    badge: "Standard d'Or",
    description: "Référence mondiale pour les agents de développement, le refactoring et l'utilisation d'outils.",
    contextLength: "200k tokens",
    supportsTools: true,
  },
  {
    id: "claude-3-5-haiku",
    name: "Claude 3.5 Haiku",
    providerId: "anthropic",
    providerName: "Anthropic Claude",
    isFree: false,
    badge: "Rapide & Précis",
    description: "Vitesse foudroyante et précision chirurgicale pour les tâches de codage légères et les tests.",
    contextLength: "200k tokens",
    supportsTools: true,
  },
  {
    id: "claude-3-opus",
    name: "Claude 3 Opus",
    providerId: "anthropic",
    providerName: "Anthropic Claude",
    isFree: false,
    badge: "Raisonnement Profond",
    description: "Conception architecturale de haut niveau, formalisation mathématique et synthèse de données complexes.",
    contextLength: "200k tokens",
    supportsTools: true,
  },

  // =========================================================================
  // OPENAI (Génération o1, o3, GPT-4o, GPT-4.5)
  // =========================================================================
  {
    id: "o3-mini",
    name: "OpenAI o3-mini",
    providerId: "openai",
    providerName: "OpenAI",
    isFree: false,
    badge: "Raisonnement STEM",
    description: "Modèle de raisonnement de pointe optimisé pour la programmation, les mathématiques et l'algorithmie.",
    contextLength: "200k tokens",
    supportsTools: true,
  },
  {
    id: "o1",
    name: "OpenAI o1",
    providerId: "openai",
    providerName: "OpenAI",
    isFree: false,
    badge: "Chaîne de Pensée",
    description: "Raisonnement approfondi avec temps de réflexion pour résoudre les problèmes d'ingénierie les plus ardus.",
    contextLength: "200k tokens",
    supportsTools: true,
  },
  {
    id: "gpt-4.5-preview",
    name: "GPT-4.5 Orion",
    providerId: "openai",
    providerName: "OpenAI",
    isFree: false,
    badge: "Frontière OpenAI",
    description: "Modèle de fondation le plus massif d'OpenAI offrant une compréhension contextuelle inégalée.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "gpt-4o",
    name: "GPT-4o",
    providerId: "openai",
    providerName: "OpenAI",
    isFree: false,
    badge: "Flagship",
    description: "Modèle multimodal polyvalent d'OpenAI combinant vitesse et grande compétence en développement.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "gpt-4o-mini",
    name: "GPT-4o Mini",
    providerId: "openai",
    providerName: "OpenAI",
    isFree: true,
    badge: "Rapide & Économique",
    description: "Modèle léger et très rapide adapté aux micro-opérations et au prototypage rapide.",
    contextLength: "128k tokens",
    supportsTools: true,
  },

  // =========================================================================
  // DEEPSEEK (Séries V3 & R1)
  // =========================================================================
  {
    id: "deepseek-r1",
    name: "DeepSeek R1",
    providerId: "deepseek",
    providerName: "DeepSeek",
    isFree: true,
    badge: "Raisonnement Libre",
    description: "Modèle de raisonnement par renforcement rivalisant avec les meilleurs modèles fermés du marché.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "deepseek-v3",
    name: "DeepSeek V3 (671B MoE)",
    providerId: "deepseek",
    providerName: "DeepSeek",
    isFree: true,
    badge: "671B MoE",
    description: "Architecture Mixture-of-Experts ultra-performante pour l'écriture de code et l'analyse système.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "deepseek-coder-33b",
    name: "DeepSeek Coder 33B",
    providerId: "deepseek",
    providerName: "DeepSeek",
    isFree: true,
    badge: "Spécialiste Code",
    description: "Spécialiste dédié à la génération de syntaxe propre, aux tests unitaires et aux algorithmes.",
    contextLength: "64k tokens",
    supportsTools: true,
  },

  // =========================================================================
  // OPENCODE ZEN (Accès Public et Modèles Open-Weights)
  // =========================================================================
  {
    id: "opencode-zen-qwen-coder",
    name: "Qwen 2.5 Coder 32B (Zen)",
    providerId: "opencode-zen",
    providerName: "OpenCode Zen",
    isFree: true,
    badge: "Zen Free",
    description: "Le meilleur modèle ouvert spécialisé dans le codage autonome et la résolution de bugs.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "opencode-zen-llama3-instruct",
    name: "Llama 3.3 70B (Zen)",
    providerId: "opencode-zen",
    providerName: "OpenCode Zen",
    isFree: true,
    badge: "Zen Free",
    description: "Modèle ouvert 70B de niveau GPT-4o pour la planification et l'ingénierie logicielle générale.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "opencode-zen-deepseek-r1",
    name: "DeepSeek R1 Distill (Zen)",
    providerId: "opencode-zen",
    providerName: "OpenCode Zen",
    isFree: true,
    badge: "Zen Free",
    description: "Raisonnement logique et décomposition analytique étape par étape sans frais d'API.",
    contextLength: "128k tokens",
    supportsTools: true,
  },

  // =========================================================================
  // MISTRAL AI (Séries Codestral & Large 2)
  // =========================================================================
  {
    id: "codestral-2501",
    name: "Codestral 25.01",
    providerId: "mistral",
    providerName: "Mistral AI",
    isFree: false,
    badge: "Codestral 2025",
    description: "Modèle de pointe européen dédié au développement logiciel, au fill-in-the-middle et aux tests.",
    contextLength: "256k tokens",
    supportsTools: true,
  },
  {
    id: "mistral-large-2411",
    name: "Mistral Large 2 (24.11)",
    providerId: "mistral",
    providerName: "Mistral AI",
    isFree: false,
    badge: "Mistral Large",
    description: "Modèle phare de 123 milliards de paramètres avec capacités multilingues et raisonnement poussé.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "pixtral-large",
    name: "Pixtral Large (124B)",
    providerId: "mistral",
    providerName: "Mistral AI",
    isFree: false,
    badge: "Vision & Code",
    description: "Modèle multimodal frontière capable d'analyser des maquettes UI, diagrammes et code source.",
    contextLength: "128k tokens",
    supportsTools: true,
  },

  // =========================================================================
  // OPENROUTER (Modèles Gratuits / Free Tier)
  // =========================================================================
  {
    id: "openrouter/deepseek/deepseek-r1:free",
    name: "DeepSeek R1 (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Raisonnement avancé par renforcement via le routeur OpenRouter sans aucun coût.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/deepseek/deepseek-chat:free",
    name: "DeepSeek V3 (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle MoE 671B haute performance pour la programmation et la génération de code.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/meta-llama/llama-3.3-70b-instruct:free",
    name: "Llama 3.3 70B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle Meta Llama 3.3 70B accessible gratuitement sur OpenRouter pour le développement.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/qwen/qwen-2.5-coder-32b-instruct:free",
    name: "Qwen 2.5 Coder 32B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Spécialiste de la programmation open-weights distribué sans frais par OpenRouter.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/google/gemini-2.0-flash-exp:free",
    name: "Gemini 2.0 Flash Exp (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Gemini 2.0 Flash Experimental disponible gratuitement via les quotas OpenRouter.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/google/gemini-2.0-flash-thinking-exp:free",
    name: "Gemini 2.0 Flash Thinking (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Gemini 2.0 Thinking Exp avec raisonnement visible gratuit via OpenRouter.",
    contextLength: "1M tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/mistralai/mistral-small-24b-instruct-2501:free",
    name: "Mistral Small 24B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle compact et efficace de Mistral AI version 25.01 gratuit sur OpenRouter.",
    contextLength: "32k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/meta-llama/llama-3.2-3b-instruct:free",
    name: "Llama 3.2 3B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle ultra-rapide pour génération instantanée et auto-complétion.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/meta-llama/llama-3.2-1b-instruct:free",
    name: "Llama 3.2 1B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle ultra-léger 1B à latence minimale pour tâches simples et suggestions de syntaxe.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/google/gemini-2.0-pro-exp-02-05:free",
    name: "Gemini 2.0 Pro Exp (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Accès gratuit au modèle expérimental Gemini 2.0 Pro via OpenRouter.",
    contextLength: "2M tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/qwen/qwen-2.5-72b-instruct:free",
    name: "Qwen 2.5 72B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle de fondation puissant 72B spécialisé en logique et programmation complexe.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/deepseek/deepseek-r1-distill-llama-70b:free",
    name: "DeepSeek R1 Distill Llama 70B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Distillation du raisonnement DeepSeek R1 sur l'architecture Meta Llama 70B.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/deepseek/deepseek-r1-distill-qwen-32b:free",
    name: "DeepSeek R1 Distill Qwen 32B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Raisonnement étape par étape compact et précis basé sur Qwen 2.5 32B.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/nousresearch/hermes-3-llama-3.1-405b:free",
    name: "Hermes 3 405B (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Le plus colossal des modèles ouverts (405 milliards) avec alignement instructif non censuré.",
    contextLength: "128k tokens",
    supportsTools: true,
  },
  {
    id: "openrouter/cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    name: "Dolphin 3.0 R1 Mistral (OpenRouter Free)",
    providerId: "openrouter",
    providerName: "OpenRouter",
    isFree: true,
    badge: "Free Tier",
    description: "Modèle de raisonnement autonome sans filtre entraîné sur l'architecture Mistral 24B.",
    contextLength: "32k tokens",
    supportsTools: true,
  },
];
